{
 "title": "Taxi Ride Duration Prediction",
 "description": "taxi ride duration prediction on Feb 2021 dataset",
 "time": { "from": "2021-01-31T20:05:58.263Z", "to": "2021-02-22T16:35:11.453Z" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "sql": {
      "columns": [],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "ride_prediction_metrics"
    },
    {},
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  prediction_drift AS \"Prediction Drift\"\nFROM ride_prediction_metrics\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Share Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM ride_prediction_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number Of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM ride_prediction_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift vs Drifted Columns vs Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {},
    {},
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  prediction_drift,\n  num_drifted_columns,\n  share_missing_values\nFROM ride_prediction_metrics\nORDER BY timestamp"
    }
   ]
  }
 ]
}